### ISSUE TITLE
Error with build - Might need updating with media and static folders 

### ISSUE THREAD

**Issue by jamestagal** [plenti-themes/compendium#6]
Hi @jimafisk @roobyz 

I would like to update my theme to include all the more recent additions to Plenti such as the new `media` and `static` folders among others but I don't think this theme has been updated. I tried to `serve` my site locally but got the following error.

```terminal
███▒▒▒▒▒▒▒ Building... 2023/03/26 19:58:51 build.go:135: 
Error in StaticCopy build stepCould not get static file from virtual theme build: open static: file does not exist
```
Could you pls have a look and let me know.  

Thanks Ben

**Comment by jimafisk** [comment]
Hey @jamestagal,

I just pushed some changes that should make this theme `v0.6.x` ready. Can you test when you get a chance and let me know if you see any issues?

Also, which version of Plenti are you using? I'm surprised that a missing `static` folder breaks your build. I tried pushing a fix for that at one point, but it's possible it needs more attention. Thanks!

**Comment by jamestagal** [comment]
Thanks @jimafisk 
I am on ❯ plenti --version v0.6.7. 
I have updated compendium now. thanks.

I got the following error:

```terminal
Building... 2023/03/27 08:34:33 build.go:153: 
Error in DataSource build step
Can't create props for content/index.json 
Could not create props for layouts_content_index_svelte
ReferenceError: layouts_content_index_svelte is not defined
    at create_ssr:1:1570
```

I will investigate more. 

Ben

**Comment by jimafisk** [comment]
Hey @jamestagal,

Sounds like you're using this as an imported theme (in your "themes" folder)? If that's that case, any override files copied from the original theme to your project need to get updated for `v0.6.x` as well. In this case, that error means you need to rename `content/index.json` to `content/_index.json`. Hope that helps!

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes thanks again. I will update my override files of the theme and let you know how I go!

Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
I updated all the obvious ones such as replacing > ```assets``` with ```media``` and I created a `static` folder and put the logos files and color-scheme.css following what you changed in the Compendium theme.

However I have one noticeable issue and that is with the font icons ```line.awesome``` I think.. they are not displaying and in the UI and as a result has prevents navigation in places where those icons should appear such as with the pagination navigation and the arrow icon in the featured posts for the slideshow on the homepage. 
See screencast

https://user-images.githubusercontent.com/6309595/227907720-0a6d4f12-1c65-4bca-b96c-87ccb860cebb.mov


Could you think of a place I might need to update the location of these icons for this to work?

**Comment by jimafisk** [comment]
I had that problem too when I first tried updating the theme to `v0.6.x`. Moving the `assets/icons8/` folder to `static/icons8/` seemed to fix it for me: https://github.com/plenti-themes/compendium/commit/d344f1d481416111e026148cacec3c9a40613a4b

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thanks fixed that problem. much appreciated. However I can't navigate through the pages on my home page and I get an 404 error. I seem to think I've had this problem before. I will try to go back through closed issue in my repo.
See screencast of issue:

https://user-images.githubusercontent.com/6309595/228087545-9e31cae5-f6c2-4fe7-b821-9cb80fab73e4.mov

Pls let me know if you can identify what the issue might be.
Thanks

**Comment by jimafisk** [comment]
You may need to update the route override in `plenti.json` to use `_index` instead of `index`?

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes you are a champion! that was it...thanks again.
all these little details in code really matter 😆  Next time when I make any underlying changes I will do a search for key words in the repo to see what else might be effected or need changing!!\
Thanks again Jim
